name: FTP Deploy for {{$__globals__/PYRONOME_PROJECT_TITLE}}
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy ENV Laravel Configuration for CI
      run: |
        php -r "file_exists('source/.env') || copy('source/.env.github-actions', 'source/.env');"
    - name: Install Composer & NPM Dependencies
      run: |
        composer install -d source -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        cd source
        npm install
        npm run prod
{{@if {{$__variables__/LARAVEL_ENV_APP_KEY}} == ''}}
    - name: Generate Laravel Application Key
      run: |
        cd source
        php artisan key:generate

{{@endif}}
    - name: Create Release Directory & Rename Public Directory
      run: |
        mkdir -p release-{{$__globals__/PYRONOME_CURRENT_DATETIME}}
        cp -a source/. release-{{$__globals__/PYRONOME_CURRENT_DATETIME}}/
        mv release-{{$__globals__/PYRONOME_CURRENT_DATETIME}}/public release-{{$__globals__/PYRONOME_CURRENT_DATETIME}}/{{$__variables__/DEPLOY_PUBLIC_DIRECTORY}}
    - name: Compress Release Directory
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r release-{{$__globals__/PYRONOME_CURRENT_DATETIME}}.zip release-{{$__globals__/PYRONOME_CURRENT_DATETIME}}/.
    - name: Create Deploy Directory
      run: |
        mkdir -p deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/{{$__globals__/PYRONOME_PROJECT_NAME}}/releases
        mkdir -p deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/{{$__variables__/DEPLOY_PUBLIC_DIRECTORY}}
        cp release-{{$__globals__/PYRONOME_CURRENT_DATETIME}}.zip deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/{{$__globals__/PYRONOME_PROJECT_NAME}}/releases/
    - name: List Deploy Folder Contents
      run: |
        echo "Listing deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/"
        ls -al deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/
        echo "Listing deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/{{$__globals__/PYRONOME_PROJECT_NAME}}/releases/"
        ls -al deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/{{$__globals__/PYRONOME_PROJECT_NAME}}/releases
        echo "Listing deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/{{$__variables__/DEPLOY_PUBLIC_DIRECTORY}}/"
        ls -al deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/{{$__variables__/DEPLOY_PUBLIC_DIRECTORY}}
    - name: Deploy Project via FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: {{$__variables__/SECRET_FTP_SERVER}}
        user: {{$__variables__/SECRET_FTP_USERNAME}}
        password: {{$__variables__/SECRET_FTP_PASSWORD}}
        localDir: "deploy-{{$__globals__/PYRONOME_RANDOM_STRING_16BYTES_LOWERCASE}}/"
        remoteDir: "/"