name: FTP Deploy for {{$__globals__/PYRONOME_PROJECT_TITLE}}
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy ENV Laravel Configuration for CI
      run: |
        php -r "file_exists('source/.env') || copy('source/.env.github-actions', 'source/.env');"
    - name: Install Composer Dependencies
      run: composer install -d source -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install NPM Dependencies
      run: |
        cd source
        npm install
        npm run prod
{{@if {{$__variables__/LARAVEL_ENV_APP_KEY}} == ''}}
    - name: Generate Laravel Application Key
      run: |
        cd source
        php artisan key:generate

{{@endif}}
    - name: Create Build Directory
      run: |
        mkdir -p build
        cp -a source/. build/
    - name: Rename Public Directory
      run: |
        mv build/public build/{{$__variables__/DEPLOY_PUBLIC_DIRECTORY}}
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r build-{{$__globals__/PYRONOME_CURRENT_DATETIME}}.zip build/.
    - name: List Root Folder Contents
      run: |
        ls -al
    - name: Deploy Build Directory via FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: {{$__variables__/SECRET_FTP_SERVER}}
        user: {{$__variables__/SECRET_FTP_USERNAME}}
        password: {{$__variables__/SECRET_FTP_PASSWORD}}
        localDir: "build-{{$__globals__/PYRONOME_CURRENT_DATETIME}}.zip"
        remoteDir: "{{$__globals__/PYRONOME_PROJECT_NAME}}/builds"